####################
# NEXUS
####################

#gradle-wrapper
#systemProp.gradle.wrapperUser=msa_dev
#systemProp.gradle.wrapperPassword=msa_dev!@

#pluginManagement credentials
NEXUS_MAVEN_PUBLIC_URL=https://nexus.iopdev.kr:31300/repository/maven-public/
#NEXUS_MAVEN_EGOV_URL=https://nexus.iopdev.kr:31300/repository/maven-public-egov/
NEXUS_USERNAME=msa_dev
NEXUS_PASSWORD=msa_dev!@


####################
# Version
####################

#plugins
springBootVersion=3.5.4
springDependencyManagementVersion=1.1.7
sonarqubeVersion=4.0.0.2929

#dependencies
eGovFrameVersion=4.3.0
#msaCmmnVersion=2025.08.25

#dependencyManagement
springCloudVersion=2025.0.0
otelVersion=1.1.2

#outer architecture
#opentelemetryVersion=1.2