
INSERT INTO TBB_PST_L (PST_SN, BBS_ID, UP_PST_SN, WRTR_ID, WRTR_NM, PST_PSWD_KEY, PST_INQ_CNT, PST_TTL, PST_CN, PST_URL_ADDR, PST_CYCL, ATCH_FILE_GROUP_ID, RLS_YN, DEL_YN, FRST_RGTR_ID, FRST_REG_DT, LAST_MDFR_ID, LAST_MDFCN_DT) 
VALUES (1, 'BBS01', null, 'test01', '테스트', 'TEST', '0', '테스트', '테스트입니다.', '', '', '', '', '', 'test01', '2025-05-27', 'test01', '2025-05-27');
