--TKC_POPUP_M 팝업기본
CREATE TABLE TKC_POPUP_M
(
	POPUP_SN           VARCHAR2(100),
	POPUP_TTL          VARCHAR2(100),
	POPUP_URL_ADDR     VARCHAR2(100),
	POPUP_PSTG_BGNG_DT VARCHAR2(100),
	POPUP_PSTG_END_DT  VARCHAR2(100),
	POPUP_WDTH_LEN     VARCHAR2(100),
	POPUP_VRTC_LEN     VARCHAR2(100),
	POPUP_USE_YN       VARCHAR2(100),
	POPUP_UNMR_USE_YN  VARCHAR2(100),
	POPUP_CN           VARCHAR2(500)
);

COMMENT ON COLUMN TKC_POPUP_M.POPUP_SN IS 'POPUP_SN';
COMMENT ON COLUMN TKC_POPUP_M.POPUP_TTL IS 'POPUP_TTL';
COMMENT ON COLUMN TKC_POPUP_M.POPUP_URL_ADDR IS 'POPUP_URL_ADDR';
COMMENT ON COLUMN TKC_POPUP_M.POPUP_PSTG_BGNG_DT IS 'POPUP_PSTG_BGNG_DT';
COMMENT ON COLUMN TKC_POPUP_M.POPUP_PSTG_END_DT IS 'POPUP_PSTG_END_DT';
COMMENT ON COLUMN TKC_POPUP_M.POPUP_WDTH_LEN IS 'POPUP_WDTH_LEN';
COMMENT ON COLUMN TKC_POPUP_M.POPUP_VRTC_LEN IS 'POPUP_VRTC_LEN';
COMMENT ON COLUMN TKC_POPUP_M.POPUP_USE_YN IS 'POPUP_USE_YN';
COMMENT ON COLUMN TKC_POPUP_M.POPUP_UNMR_USE_YN IS 'POPUP_UNMR_USE_YN';
COMMENT ON COLUMN TKC_POPUP_M.POPUP_CN IS 'POPUP_CN';
COMMENT ON TABLE TKC_POPUP_M IS '팝업기본';

CREATE UNIQUE INDEX TKC_POPUP_M_PK ON TKC_POPUP_M ( POPUP_SN );

ALTER TABLE TKC_POPUP_M
    ADD CONSTRAINT 엔터티3_PK1 PRIMARY KEY ( POPUP_SN )
    USING INDEX TKC_POPUP_M_PK;

--TBB_PST_L 게시물상세
CREATE TABLE TBB_PST_L
(
    PST_SN             VARCHAR2(100),
    BBS_ID             VARCHAR2(100),
    UP_PST_SN          VARCHAR2(100),
    WRTR_ID            VARCHAR2(100),
    WRTR_NM            VARCHAR2(100),
    PST_PSWD_KEY       VARCHAR2(100),
    PST_INQ_CNT        VARCHAR2(100),
    PST_TTL            VARCHAR2(100),
    PST_CN             VARCHAR2(500),
    PST_URL_ADDR       VARCHAR2(100),
    PST_CYCL           VARCHAR2(100),
    ATCH_FILE_GROUP_ID VARCHAR2(100),
    RLS_YN             VARCHAR2(100),
    DEL_YN             VARCHAR2(100),
    FRST_RGTR_ID       VARCHAR2(100),
    FRST_REG_DT        VARCHAR2(100),
    LAST_MDFR_ID       VARCHAR2(100),
    LAST_MDFCN_DT      VARCHAR2(100)
);

COMMENT ON COLUMN TBB_PST_L.PST_SN IS 'PST_SN';
COMMENT ON COLUMN TBB_PST_L.BBS_ID IS 'BBS_ID';
COMMENT ON COLUMN TBB_PST_L.UP_PST_SN IS 'UP_PST_SN';
COMMENT ON COLUMN TBB_PST_L.WRTR_ID IS 'WRTR_ID';
COMMENT ON COLUMN TBB_PST_L.WRTR_NM IS 'WRTR_NM';
COMMENT ON COLUMN TBB_PST_L.PST_PSWD_KEY IS 'PST_PSWD_KEY';
COMMENT ON COLUMN TBB_PST_L.PST_INQ_CNT IS 'PST_INQ_CNT';
COMMENT ON COLUMN TBB_PST_L.PST_TTL IS 'PST_TTL';
COMMENT ON COLUMN TBB_PST_L.PST_CN IS 'PST_CN';
COMMENT ON COLUMN TBB_PST_L.PST_URL_ADDR IS 'PST_URL_ADDR';
COMMENT ON COLUMN TBB_PST_L.PST_CYCL IS 'PST_CYCL';
COMMENT ON COLUMN TBB_PST_L.ATCH_FILE_GROUP_ID IS 'ATCH_FILE_GROUP_ID';
COMMENT ON COLUMN TBB_PST_L.RLS_YN IS 'RLS_YN';
COMMENT ON COLUMN TBB_PST_L.DEL_YN IS 'DEL_YN';
COMMENT ON COLUMN TBB_PST_L.FRST_RGTR_ID IS 'FRST_RGTR_ID';
COMMENT ON COLUMN TBB_PST_L.FRST_REG_DT IS 'FRST_REG_DT';
COMMENT ON COLUMN TBB_PST_L.LAST_MDFR_ID IS 'LAST_MDFR_ID';
COMMENT ON COLUMN TBB_PST_L.LAST_MDFCN_DT IS 'LAST_MDFCN_DT';
COMMENT ON TABLE TBB_PST_L IS '게시물상세';

CREATE UNIQUE INDEX TBB_PST_L_PK ON TBB_PST_L ( PST_SN );

ALTER TABLE TBB_PST_L
    ADD CONSTRAINT 엔터티3_PK2 PRIMARY KEY ( PST_SN )
    USING INDEX TBB_PST_L_PK;

